name: fl_qr_reader
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.0
  provider: ^6.0.5
  flutter_barcode_scanner: ^2.0.0
  path_provider: ^2.0.15
  sqflite: ^2.2.8+4
  url_launcher: ^6.1.11
  google_maps_flutter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
